config/routes.rb
Rails.application.routes.draw do
  resources :papers

  root 'home#index'
 
   

  resources :authors

  

end

app/models/application_record.rb
# By default all new Rails 5 applications will have application_record.rb.
# If you are migrating from Rails 4, then simply create app/models/application_record.rb
# as shown below and change all models to inherit from ApplicationRecord instead of ActiveRecord::Base.
# https://stackoverflow.com/questions/41387706/uninitialized-constant-applicationrecord-error#41388844
# https://blog.bigbinary.com/2015/12/28/application-record-in-rails-5.html
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    validates :last_name, presence: true,
                          length: {minimum: 1}  
    has_and_belongs_to_many :papers
    def name
        first_name + " " + last_name
    end
end

app/models/paper.rb
class Paper < ApplicationRecord
    
    validates :title, presence: true, length: {minimum: 1} 
    validates :venue, presence: true, length: {minimum: 1} 
    validates :year, presence: true, numericality: true, length: {minimum: 1}

    scope :published, -> (year_in) {where("year = ?", year_in)}
    
    has_and_belongs_to_many :authors

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    def index
        @authors = Author.all  
    end

    def show
        @author = Author.find(params[:id]) 
    end
    
    def new 
        @author= Author.new
    end

    def edit
        @author = Author.find(params[:id])
      end

    def create 
        @author = Author.new(authors_params)

        if @author.save
            redirect_to @author, notice: 'Success!'
        else
            render "new"
        end 
    end
    
    def update
        @author = Author.find(params[:id])
       
        if @author.update(authors_params)
            redirect_to @author
        else
            render 'edit'
        end
    end
        
    def destroy
        @author = Author.find(params[:id])
        @author.destroy
   
        redirect_to authors_path
    end
        


    private 
        def authors_params
            params.require(:author).permit(:first_name, :last_name, :homepage)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: [:show, :edit, :update, :destroy]

  # GET /papers
  def index
    if params[:year]
      @papers = Paper.published(params[:year])
    else
      @papers = Paper.all
    end
  end

  # GET /papers/1
  def show
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers
  def create
    @paper = Paper.new(paper_params)

    if @paper.save
      redirect_to @paper, notice: 'Paper was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /papers/1
  def update
    if @paper.update(paper_params)
      redirect_to @paper, notice: 'Paper was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /papers/1
  def destroy
    @paper.destroy
    redirect_to papers_url, notice: 'Paper was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def paper_params
      params.require(:paper).permit(:title, :venue, :year, :author_ids => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/authors/edit.html.erb
<h1>Edit Author</h1>
 
<%= form_with(model: @author, local: true) do |form| %>
 
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@author.errors.count, "error") %> prohibited
        this author from being saved:
      </h2>
      <ul>
        <% @author.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>
 
  <p>
    <%= form.label :last_name %><br>
    <%= form.text_area :last_name%>
  </p>
  <p>
    <%= form.label :homepage %><br>
    <%= form.text_area :Homepage%>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing Authors</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Homepage</th>
    <th></th>
  </tr>
 
  <% @authors.each do |author| %>
    <tr>
      <td><%= author.name %></td>
      <td><%= author.homepage %></td>
      <td><%= link_to 'Show', author_path(author) %></td>
      <td><%= link_to 'Edit', edit_author_path(author) %></td>
      <td><%= link_to 'Delete', author_path(author),
              method: :delete %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'New ', new_author_path %>

app/views/authors/new.html.erb
<h1>New Authors</h1>

<%= form_with scope: :author,url: authors_path, local: true do |form| %>

 <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@author.errors.count, "error") %> prohibited
        this author from being saved:
      </h2>
      <ul>
        <% @author.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= form.label :first_name %><br>
    <%= form.text_area :first_name %>
  </p>
 
  <p>
    <%= form.label :last_name %><br>
    <%= form.text_area :last_name %>
  </p>
  <p>
    <%= form.label :homepage %><br>
    <%= form.text_area :homepage %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/authors/show.html.erb
<p>
<strong>FirstName:</strong>
<%= @author.first_name %>
</p>
<p>
<strong>LastName:</strong>
<%= @author.last_name %>
</p>
<p>
<strong>Homepage:</strong>
<%= @author.homepage %>
</p>

 

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paper Management System</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SWT II Intro Exercise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/papers/_form.html.erb
<%= form_with(model: paper, local: true) do |form| %>
  <% if paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
        <% paper.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :venue %>
    <%= form.text_field :venue %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :authors %>
    <%= form.select 'author_ids',
      options_from_collection_for_select(Author.all, :id, :name, paper.author_ids),
      {},
      multiple: true, size: 10 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/papers/edit.html.erb
<h1>Editing Paper</h1>

<%= render 'form', paper: @paper %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

app/views/papers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Papers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Venue</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @papers.each do |paper| %>
      <tr>
        <td><%= paper.title %></td>
        <td><%= paper.venue %></td>
        <td><%= paper.year %></td>
        <td><%= link_to 'Show', paper %></td>
        <td><%= link_to 'Edit', edit_paper_path(paper) %></td>
        <td><%= link_to 'Destroy', paper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paper', new_paper_path %>

app/views/papers/new.html.erb
<h1>New Paper</h1>

<%= render 'form', paper: @paper %>

<%= link_to 'Back', papers_path %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @paper.title %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @paper.venue %>
</p>

<p>
  <strong>Year:</strong>
  <%= @paper.year %>
</p>
<p>
  <strong>Author:</strong>
  <% @paper.authors.each do |author| %>
    <%= author.name %><br>
  <% end %>
</p>

<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>